### ISSUE TITLE
Link errors on linux due to pthread dependency

### ISSUE THREAD

**Issue by stedolan** [janestreet/spawn#1]
When compiling a program that links against `spawn` (@yomimono's [bun](https://github.com/yomimono/ocaml-bun)), I get many link errors:

```
/home/stephen/.opam/4.05.0+afl/lib/spawn/libspawn_stubs.a(spawn_stubs.o): In function `spawn_unix':
/home/stephen/.opam/4.05.0+afl/build/spawn.v0.9.0/_build/default/src/spawn_stubs.c:396: undefined reference to `pthread_sigmask'
/home/stephen/.opam/4.05.0+afl/build/spawn.v0.9.0/_build/default/src/spawn_stubs.c:440: undefined reference to `pthread_sigmask'
/home/stephen/.opam/4.05.0+afl/lib/spawn/libspawn_stubs.a(spawn_stubs.o): In function `subprocess':
/home/stephen/.opam/4.05.0+afl/build/spawn.v0.9.0/_build/default/src/spawn_stubs.c:233: undefined reference to `pthread_sigmask'
/home/stephen/.opam/4.05.0+afl/lib/spawn/libspawn_stubs.a(spawn_stubs.o): In function `subprocess_failure':
/home/stephen/.opam/4.05.0+afl/build/spawn.v0.9.0/_build/default/src/spawn_stubs.c:151: undefined reference to `pthread_sigmask'
```

The issue is that `pthread_sigmask` is unavailable unless the program is being linked with `-lpthread`, which is only the case if the threaded runtime is selected. Adding `threads` to `jbuild` as a dependency fixes this.

`spawn` should either depend on `threads`, or avoid using pthread functions.

**Comment by yomimono** [comment]
@trefis ping? I'm keeping a fork that fixes this problem by inserting a hard dependency in `jbuild`.  I'd like to release the software that depends on it soon, and this will be a blocker.

**Comment by diml** [comment]
Ok, I added a dependency on threads. BTW, I talked to the other devs of the library and we are happy to move the development directly to github. This will make things easier moving forward.

**Comment by yomimono** [comment]
Thanks for both, @diml!

**Comment by diml** [comment]
No problems, I managed to get opam-publish to do the release: https://github.com/ocaml/opam-repository/pull/11082
