### ISSUE TITLE
Windows: Unicode characters in the program name/path makes spawn fail

### ISSUE THREAD

**Issue by kit-ty-kate** [janestreet/spawn#57]
According to [its documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa), `CreateProcess` defaults to the ASCII if `UNICODE` is not defined.

I'm not able to find this macro defined anywhere in spawn and in any case, `v_prog` is passed as-is to `CreateProcess` which means the string is not UTF-16 encoded.

If you call `spawn` on Windows with `~prog:"C:\path\to\a\Unicěde.exe"` the process will fail with:
```
Error: CreateProcess(): No such file or directory
```

**Comment by nojb** [comment]
Indeed, `CreateProcessW` should be used (instead of `CreateProcess`) and the command line should be recoded to UTF-16.

**Comment by dra27** [comment]
A side-note - it's better to define `_UNICODE` and `UNICODE` (cf. https://github.com/ocaml/opam/blob/master/src/stubs/win32/dune-win32#L11-L16 but also [Raymond says so](https://devblogs.microsoft.com/oldnewthing/20040212-00/?p=40643) [twice](https://devblogs.microsoft.com/oldnewthing/20211210-00/?p=106021)) than use the `W` functions directly. MSDN [suggests you can do either](https://learn.microsoft.com/en-us/windows/win32/learnwin32/working-with-strings) but in practice setting those defines at the level of the compiler call unusually provides some C type safety.

**Comment by dra27** [comment]
Just to add that I have a fix for this (tested in Dune vendored in opam so) - I'll endeavour to get this turned into the requisite series of PRs to spawn and Dune.
