### ISSUE TITLE
Which OS are supported?

### ISSUE THREAD

**Issue by vog** [janestreet/spawn#6]
Since this library is not plain OCaml, but contains C code, it is important to know which operating systems are supported.

In particular, how portable is the Unix-part of the C code? Does it only work on Linux, or does it work on OpenBSD, FreeBSD and MacOS, too?

**Comment by diml** [comment]
It is expected to be fully portable. However, so far it has only be tested on Linux, OSX and Windows.

**Comment by vog** [comment]
Would you mind adding that to a suitable place in the documentation? (e.g. README or the doc comment on the `spawn` interface)

**Comment by diml** [comment]
Sure, I added a line about this in the README
