### ISSUE TITLE
Proposal: Combine the "prog" and "argv" arguments

### ISSUE THREAD

**Issue by vog** [janestreet/spawn#7]
I propose to combine the two arguments `prog` and `argv` into a single argument, which could be a tuple `(prog, argv)` or an abstract type containing that tuple.

That would allow us to define helper functions for most standard situations:

1. The first element for `argv` is equal to `prog`:
```ocaml
let of_args args = (List.hd args, args)
```
2. A shell command is to be executed:
```ocaml
let of_cmd cmd = of_args ["/bin/sh", "-c", cmd]
```
3. In case an abstract type is used, an identity function would be needed as well:
```
let of_prog_argv prog argv = (prog, argv)
```

Since that change would not be backwards compatible, I propose to add a new function `spawn2`, which could also provide the no-fork feature as proposed in #8. The old `spawn` function could be implemented in terms of `spawn2`, and be perhaps be marked deprecated.

**Comment by diml** [comment]
Spawn is more meant to be a backend library. You might want to look at [shexp](https://github.com/janestreet/shexp).

**Comment by vog** [comment]
Thanks for the pointer.
