### ISSUE TITLE
Proposal: Add non-forking variant

### ISSUE THREAD

**Issue by vog** [janestreet/spawn#8]
I propose to add to possibility that `spawn` executes `execve` directly in the current process, without forking.

Use case: an OCaml program which is mainly a preprocessing/configuration wrapper over another program. If the latter is a long running process, it would save resources if the initial OCaml program no longer runs. Also, a running supervisor process should catch the new program rather than the OCaml wrapper. It would be great if that could be achived using (almost) the same interface as with forking.

Ideas for interface changes:

1. While it may be tempting to extend `Unix_backend.t` with a third variant `NoFork`, I'd propose not to do that. First, that change would not be 100% backwards compatible: Client code would suddenly fail to compile if it called the public function `Unix_backend.default` and pattern matched the result. Second, it would blurr implementation details (fork vs. vfork) with an actual change in the obserable behaviour.
2. Another possibility would be to add an optional `boolean` label argument to `spawn`. However, I'm not sure if that change would be 100% backwards compatible. But it would be at least 99.999%, I guess.
3. The additional argument could go into the new function `spawn2` as proposed in #7. That would be 100% safe.

**Comment by diml** [comment]
What would be the benefit compared to calling `Unix.execve` directly?

**Comment by vog** [comment]
The advantage would be a uniform interface for forking and non-forking calls. Moreover, Unix.execve does not provide facilities to redirect stdin/stdout/stderr.

**Comment by diml** [comment]
Ok, I could be convinced. @aalekseyev any opinion on this?

One negative point is that this cannot be supported on Windows.

Regarding the API, it seems clear to me that this should be a separate function, as `spawn` is pretty much always associated to starting something in the background.

**Comment by aalekseyev** [comment]
I think the benefit from uniform interface between forking and non-forking is pretty small: they are approximately never interchangeable as they lead to very different behavior.

Also, I think the overlap in implementation will be minimal: we'd probably just end up using [Unix.execve] as our backend, no?

Combined with the fact that it won't work on Windows, I think I lean towards not having it here.

**Comment by vog** [comment]
Thanks for pointing this out. So it seems that adding a non-forking variant is not as beneficial as I initially thought.
